[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
BetaRegression = "2339b9c3-daaf-4eaa-90d5-e8471159c344"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CameraCalibrations = "70c3cbac-2c23-4b2d-966c-5a25c0a540fb"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
